name: Notadd Manaco 编辑器
identification: notadd/ext-monaco
description:
author:
    - Notadd
    - notadd@ibenchu.com
provider: Notadd\Monaco\Addon
assets:
    administration:
        notadd/mall-gallery:
            permissions:
            scripts: assets/addons/notadd/monaco/administration/js/addon.min.js
publishes:
    assets/extensions/notadd/monaco/ediotr: resources/mixes/editor
    assets/addons/notadd/monaco/administration: resources/mixes/administration/dist/assets/addons/notadd/monaco/administration