name: Notadd Manaco 编辑器
identification: notadd/ext-monaco
description:
author:
    - Notadd
    - notadd@ibenchu.com
provider: Notadd\Monaco\Extension
publishes:
    assets/extensions/notadd/monaco: resources/mixes