name: Notadd Manaco 编辑器
identification: notadd/ext-monaco
description:
author:
    - Notadd
    - notadd@ibenchu.com
provider: Notadd\Monaco\Addon
publishes:
    assets/extensions/notadd/monaco/ediotr: resources/mixes/editor